version: "3.6"

services:
  app:
    build: .
    command: python entrypoint.py
    env_file:
      - .env
    volumes:
      - ./src:/src
    ports:
      - $EXPOSED_PORT:$INTERNAL_PORT
    restart: unless-stopped
